language: python

install:
  - pip install -r requirements.txt
  - pip install pytest==5.2.0 pytest-cov==2.5.1 pytest-pep8 coveralls
  - python -m spacy download en_core_web_sm
# command to run tests
script:
  - python -m pytest --cov=utils utils

after_success:
  - coveralls
